baseURL = 'https://blog.heikkihakala.fi'
languageCode = 'fi'
defaultContentLanguage = 'fi'
title = 'Heikki Hakala'
theme = 'introduction'

[params]
    dateFormat	 = "02 Jan 2006"
    fadeIn       = false
    fadeInIndex  = false
    customCSS 	 = ["css/train.css"]
    customJS 	 = ["js/Polyline.encoded.js", "js/train.js"]

# Social icons appear in introduction and contact section. Add as many more as you like.
# Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
# Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
[[params.social]]
url   = "https://twitter.com/heikkihakalafi"
icon  = "twitter" # icon name without the 'fa-'
icon_pack = "fab"
[[params.social]]
url   = "https://github.com/hhakala"
icon  = "github" # icon name without the 'fa-'
icon_pack = "fab"
[[params.social]]
url   = "https://www.strava.com/athletes/71447788"
icon  = "strava" # icon name without the 'fa-'
icon_pack = "fab"

[params.share]
twitter                  = true

# If you don't want to use the default menu, you can define one by yourself
[[menu.main]]
    name    = "Etusivu"
    url     = "/"
    weight  = 1
[[menu.main]]
    name    = "Juoksu"
    url     = "/run/"
    weight  = 2
[[menu.main]]
    name    = "Kävely"
    url     = "/walk/"
    weight  = 3
[[menu.main]]
    name    = "Liikkuvuus"
    url     = "/workout/"
    weight  = 4
[[menu.main]]
    name    = "Voima"
    url     = "/weighttraining/"
    weight  = 5
[[menu.main]]
    name    = "Yoga"
    url     = "/yoga/"
    weight  = 6




[languages]
    [languages.fi]
        languageName     = "Suomi"
        languageCode     = "fi"
        contentDir       = "content/"
        weight           = 0
        title            = "Heikki Hakalan urheilublogi"
        [languages.fi.params]
            description  = "Heikki Hakalan urheilublogi"
            footerText   = "”Jokainen syy, joka estää kuntoilun, on tekosyy.” -Urho Kekkonen"